version: '3.8'

services:

  terraform:
    container_name: terraform
    platform: linux/amd64
    image: "hashicorp/terraform:latest"
    restart: unless-stopped
    working_dir: /config
    volumes:
      - ./config:/config
    labels:
      com.datadoghq.ad.logs: '[{"source": "terraform", "service": "terraform"}]'
    environment:
      - DD_SERVICE="terraform"
      - DD_ENV
      - DD_VERSION
    command: tail -f /dev/null