services:

  webapp:
    container_name: webapp
    platform: linux/amd64
    build: webapp/build/.
    command: ddtrace-run gunicorn -w 2 -b :8000 --timeout 60 wsgi:app
    volumes:
      - ./webapp:/webapp
    environment:
      - DD_SERVICE=webapp
      - DD_ENV
      - DD_VERSION
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
      - DD_CLIENT_TOKEN
      - DD_APPLICATION_ID
      - REDIS_HOST=redis
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "webapp", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\[?\\d{4}-\\d{2}-\\d{2}"}]}]'
    ports:
      - 8000:8000
